<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
	</PropertyGroup>
	<Import Project="../MainSlnCommon.props" />
	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(ProjectDir)../../../extern/tools/NLua/NLua.csproj" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" />
		<PackageReference Include="SharpCompress" PrivateAssets="all" NoWarn="NU1902" />
		<PackageReference Include="SQLitePCLRaw.provider.e_sqlite3" />
		<PackageReference Include="System.Drawing.Common" PrivateAssets="all" />
		<PackageReference Include="System.CommandLine" />
		<ProjectReference Include="$(ProjectDir)../Chimera.Bizware.Graphics/Chimera.Bizware.Graphics.csproj" />
		<ProjectReference Include="$(ProjectDir)../Chimera.Bizware.Input/Chimera.Bizware.Input.csproj" />
		<ProjectReference Include="$(ProjectDir)../Chimera.Emulation.Common/Chimera.Emulation.Common.csproj" />
		<EmbeddedResource Include="Resources/**/*" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="movie/base/MovieBase.HeaderApi.cs" DependentUpon="MovieBase.cs" />
		<Compile Update="movie/base/MovieBase.InputLog.cs" DependentUpon="MovieBase.cs" />
		<Compile Update="movie/base/MovieBase.IO.cs" DependentUpon="MovieBase.cs" />
		<Compile Update="movie/base/MovieBase.ModeApi.cs" DependentUpon="MovieBase.cs" />
		<Compile Update="movie/tasproj/TasMovie.Editing.cs" DependentUpon="TasMovie.cs" />
		<Compile Update="movie/tasproj/TasMovie.IO.cs" DependentUpon="TasMovie.cs" />
	</ItemGroup>
</Project>
