#nullable enable

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using Chimera.Common;
using Chimera.Common.PathExtensions;

namespace Chimera.Client.Common
{
	/// <summary>
	/// Where a project's regenerable things live: the state history, and where
	/// this machine last found the project's files.
	///
	/// The rule is that a <c>.chimeraProject</c> is the ONE file that exists as
	/// far as anyone else is concerned. It is what gets handed over, and what
	/// gets synced to a cloud folder; everything else about a project can be
	/// recomputed from it, so nothing else belongs beside it. That is not
	/// tidiness: projects live in synced folders - a multi-gigabyte state
	/// history next to one would be uploaded on every save, and the sync client
	/// holds files open while it works.
	///
	/// So the rest lives here instead, per user and per project, keyed by the
	/// project's own id rather than by its path. A path is true of one machine
	/// and stops being true the moment the file is renamed or moved; an id
	/// survives all of that, and survives the same project being opened on
	/// another machine through a synced folder. Two attempts at the same game
	/// have different ids and so cannot share a cache, which anything derived
	/// from the contents would have got wrong.
	///
	/// Losing all of this costs recomputation and never work, which is the rule
	/// the state history has always been held to. Deleting the directory is a
	/// supported thing to do.
	/// </summary>
	public static class ProjectCache
	{
		/// <summary>
		/// The root everything per-project hangs under. Follows the core store
		/// (see <see cref="CoreStore"/>): <c>CHIMERA_DATA_HOME</c> wins where it is
		/// set, then the platform's per-user data location.
		///
		/// Worked out on every ask rather than cached, so that changing
		/// <c>CHIMERA_DATA_HOME</c> takes effect - which is what a portable install
		/// wants, and what lets a test point the cache at a temporary directory
		/// instead of at the machine's real one. It is a few string joins.
		/// </summary>
		public static string Root => Path.Combine(DataHome, DirName);

		/// <summary>
		/// The per-user directory Chimera keeps its own things under, of which the
		/// project caches are one. Named here because more than the projects live
		/// in it - the lock book does too (see <see cref="CacheLocks"/>) - and
		/// everything that does has to agree about where "here" is.
		/// </summary>
		public static string DataHome => Resolve();

		private const string DirName = "Projects";

		private static string Resolve()
		{
			var dataHome = Environment.GetEnvironmentVariable("CHIMERA_DATA_HOME");
			if (!string.IsNullOrWhiteSpace(dataHome)) return dataHome!;
			if (OSTailoredCode.IsUnixHost)
			{
				var xdg = Environment.GetEnvironmentVariable("XDG_DATA_HOME");
				var home = Environment.GetEnvironmentVariable("HOME") ?? ".";
				var baseDir = string.IsNullOrWhiteSpace(xdg) ? Path.Combine(home, ".local", "share") : xdg!;
				return Path.Combine(baseDir, "chimera");
			}
			var local = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.DoNotVerify);
			if (string.IsNullOrWhiteSpace(local)) return PathUtils.DataDirectoryPath;
			return Path.Combine(local, "Chimera");
		}

		/// <summary>
		/// This project's directory. Not created by asking; see <see cref="Ensure"/>.
		/// An id that is empty or holds anything but plain hex is refused a
		/// directory of its own and given "unidentified" - a project file somebody
		/// hand-edited must not be able to name a path.
		/// </summary>
		public static string DirectoryFor(string projectId) => Path.Combine(Root, Safe(projectId));

		/// <summary>Creates this project's directory if it is not there, and returns it.</summary>
		public static string Ensure(string projectId)
		{
			var dir = DirectoryFor(projectId);
			Directory.CreateDirectory(dir);
			return dir;
		}

		/// <summary>
		/// Who this cache belongs to: what the project calls itself, the machine it
		/// runs, the game it runs, and where its file was when it was last opened or
		/// saved. Written on both, so the cache manager can show what a person
		/// recognises instead of sixteen hex digits - and so somebody deciding what
		/// to reclaim can tell a PlayStation 3 disc from a NES cartridge without
		/// opening anything.
		///
		/// The path is a note, not a claim. A project moves, and the cache follows
		/// it by id rather than by path, so this may name somewhere the file no
		/// longer is - which is worth SAYING, because a cache whose project has
		/// gone is exactly the one worth reclaiming.
		///
		/// Every field is optional and only ever a label. Nothing reads it back to
		/// decide anything, which is why it can be regenerated by opening the
		/// project once and is no loss when it is not there.
		/// </summary>
		public static void Remember(string projectId, ProjectFacts facts)
		{
			try
			{
				var known = AboutOf(projectId);
				JObject root = new()
				{
					["title"] = Pick(facts.Title, known.Title),
					["projectPath"] = facts.ProjectPath.Length is not 0 ? FullPath(facts.ProjectPath) : known.ProjectPath,
					["core"] = Pick(facts.Core, known.Core),
					["system"] = Pick(facts.System, known.System),
					["games"] = new JArray((facts.Games.Count is not 0 ? facts.Games : known.Games).Cast<object>().ToArray()),
				};
				Ensure(projectId);
				File.WriteAllText(Path.Combine(DirectoryFor(projectId), LabelFile), root.ToString(Formatting.Indented));
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
			{
				// a note that cannot be written costs a less friendly list, nothing more
			}
		}

		private static string Pick(string fresh, string known) => string.IsNullOrWhiteSpace(fresh) ? known : fresh.Trim();

		private static string FullPath(string path)
		{
			try
			{
				return Path.GetFullPath(path);
			}
			catch (Exception ex) when (ex is ArgumentException or NotSupportedException or PathTooLongException)
			{
				return path;
			}
		}

		/// <summary>What the cache was told about a project. Every field may be empty.</summary>
		public sealed class ProjectFacts
		{
			public string Title { get; init; } = "";

			public string ProjectPath { get; init; } = "";

			/// <summary>The core it is pinned to, by name.</summary>
			public string Core { get; init; } = "";

			/// <summary>The machine, as the movie records it: XBOX, NES, PS2.</summary>
			public string System { get; init; } = "";

			/// <summary>The game's own files - the media, not the cue's tracks.</summary>
			public IReadOnlyList<string> Games { get; init; } = Array.Empty<string>();
		}

		/// <summary>
		/// Everything the cache wants to know, read off a project. One place, so
		/// the two callers that remember - opening and saving - agree about what a
		/// project's machine and game are called.
		///
		/// The game is the media, not the tracks: a cue's bins arrive in the
		/// reserved "support" slot and naming them would bury the disc they belong
		/// to under its own contents.
		/// </summary>
		public static ProjectFacts FactsOf(Chimera.Emulation.Common.Engine.EngineProject project, string projectPath)
		{
			List<string> games = new();
			for (var i = 0; i < project.FileCount; i++)
			{
				if (string.Equals(project.FileSlot(i), "support", StringComparison.OrdinalIgnoreCase)) continue;
				games.Add(project.FileName(i));
			}
			return new ProjectFacts
			{
				Title = project.Title,
				ProjectPath = projectPath ?? "",
				Core = project.CoreName,
				System = project.HeaderGet("Platform") ?? "",
				Games = games,
			};
		}

		/// <summary>What the cache was told about this project; empty when it never was.</summary>
		public static ProjectFacts AboutOf(string projectId)
		{
			try
			{
				var path = Path.Combine(DirectoryFor(projectId), LabelFile);
				if (!File.Exists(path)) return new ProjectFacts();
				var root = JObject.Parse(File.ReadAllText(path));
				return new ProjectFacts
				{
					Title = root.Value<string>("title") ?? "",
					ProjectPath = root.Value<string>("projectPath") ?? "",
					Core = root.Value<string>("core") ?? "",
					System = root.Value<string>("system") ?? "",
					Games = (root["games"] as JArray)?.Select(t => t.Value<string>() ?? "").Where(static g => g.Length is not 0).ToList()
						?? (IReadOnlyList<string>)Array.Empty<string>(),
				};
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or Newtonsoft.Json.JsonException)
			{
				return new ProjectFacts();
			}
		}

		private const string LabelFile = "about.json";

		private const string BudgetsFile = "budgets.json";

		/// <summary>
		/// What ONE project's greenzone may weigh, where it differs from the
		/// defaults. Null for either half means "whatever the settings say".
		///
		/// Here and not in the <c>.chimeraProject</c> on purpose. The project file
		/// holds what affects sync and reproduction and nothing else (docs/project.md),
		/// and a budget affects neither: it decides how much of a run stays
		/// reachable without replaying, which is a property of the MACHINE the work
		/// is being done on. A project handed to somebody with half the memory must
		/// not arrive carrying a number chosen for a machine they do not have.
		/// </summary>
		public sealed class ProjectBudgets
		{
			public int? MemoryMb { get; init; }

			public bool Any => MemoryMb.HasValue;
		}

		/// <summary>
		/// Deletes the spill files a history left in this project's directory, and says how many.
		///
		/// Chimera keeps a greenzone in memory only (user-decided, 2026-09-15), so nothing
		/// writes these any more - and nothing sweeps them either: the engine only sweeps
		/// when it is given a directory to spill into, and it no longer is. A file an earlier
		/// build left is gigabytes of nothing, named for a process that has ended. A file
		/// another process still holds open refuses to go on Windows, which is the right
		/// answer, and is simply left.
		/// </summary>
		public static int DeleteSpillFiles(string projectId)
		{
			var dir = DirectoryFor(projectId);
			if (!Directory.Exists(dir)) return 0;
			var removed = 0;
			foreach (var file in Directory.EnumerateFiles(dir, "history-spill-*.bin"))
			{
				try
				{
					File.Delete(file);
					removed++;
				}
				catch (IOException) { }
				catch (UnauthorizedAccessException) { }
			}
			return removed;
		}

		/// <summary>What this project asked for, or nothing if it never asked.</summary>
		public static ProjectBudgets BudgetsOf(string projectId)
		{
			try
			{
				var path = Path.Combine(DirectoryFor(projectId), BudgetsFile);
				if (!File.Exists(path)) return new ProjectBudgets();
				var root = JObject.Parse(File.ReadAllText(path));
				return new ProjectBudgets
				{
					MemoryMb = (int?) root["memoryMb"],
				};
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException
				or ArgumentException or JsonException)
			{
				// unreadable is the same as absent: the defaults apply and nothing is lost
				return new ProjectBudgets();
			}
		}

		/// <summary>
		/// Remembers what one project asked for. Writing budgets with nothing set
		/// removes the file, so "back to the default" leaves no trace to explain
		/// later.
		/// </summary>
		public static void RememberBudgets(string projectId, ProjectBudgets budgets)
		{
			try
			{
				var path = Path.Combine(DirectoryFor(projectId), BudgetsFile);
				if (!budgets.Any)
				{
					if (File.Exists(path)) File.Delete(path);
					return;
				}
				JObject root = new();
				if (budgets.MemoryMb.HasValue) root["memoryMb"] = budgets.MemoryMb.Value;
				root.Remove("diskMb");   /* a budget earlier builds kept; nothing reads it now */
				Ensure(projectId);
				File.WriteAllText(path, root.ToString(Formatting.Indented));
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
			{
				// the default applies, which is what was happening a moment ago anyway
			}
		}

		/// <summary>
		/// Every project this machine has cached anything for: the id, what it
		/// calls itself, how much room it takes and when it was last touched.
		/// Nothing here is authority - a directory whose project has been deleted
		/// is listed exactly like one whose project is sitting open.
		/// </summary>
		public static IReadOnlyList<CachedProject> All()
		{
			List<CachedProject> found = new();
			try
			{
				if (!Directory.Exists(Root)) return found;
				foreach (var dir in Directory.EnumerateDirectories(Root))
				{
					var id = Path.GetFileName(dir);
					long bytes = 0;
					var touched = DateTime.MinValue;
					try
					{
						foreach (var f in new DirectoryInfo(dir).EnumerateFiles("*", SearchOption.AllDirectories))
						{
							bytes += f.Length;
							if (f.LastWriteTimeUtc > touched) touched = f.LastWriteTimeUtc;
						}
					}
					catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
					{
						// a directory that will not be measured is still worth listing
					}
					var about = AboutOf(id);
					found.Add(new CachedProject
					{
						Id = id,
						Label = about.Title,
						ProjectPath = about.ProjectPath,
						Core = about.Core,
						System = about.System,
						Games = about.Games,
						Path = dir,
						Bytes = bytes,
						LastUsed = touched,
					});
				}
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
			{
				return found;
			}
			return found;
		}

		/// <summary>One project's cache, as the cache manager lists it.</summary>
		public sealed class CachedProject
		{
			public string Id { get; init; } = "";

			/// <summary>What the project calls itself, or "" when the cache never learned.</summary>
			public string Label { get; init; } = "";

			/// <summary>Where the project's file was last seen, or "" when unknown.</summary>
			public string ProjectPath { get; init; } = "";

			/// <summary>The core it is pinned to, the machine that core runs, and the game.</summary>
			public string Core { get; init; } = "";

			public string System { get; init; } = "";

			public IReadOnlyList<string> Games { get; init; } = Array.Empty<string>();

			public string Path { get; init; } = "";

			public long Bytes { get; init; }

			public DateTime LastUsed { get; init; }
		}

		/// <summary>Forgets everything cached for one project. Costs recomputation, never work.</summary>
		public static void Forget(string projectId)
		{
			try
			{
				var dir = DirectoryFor(projectId);
				if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true);
			}
			catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
			{
				// a cache that will not go is not worth an error: it is only a cache
			}
		}

		/// <summary>
		/// An id reduced to what may safely name a directory. The engine mints
		/// sixteen hex characters; anything else came from an edited file.
		/// </summary>
		private static string Safe(string projectId)
		{
			if (string.IsNullOrWhiteSpace(projectId)) return "unidentified";
			foreach (var c in projectId)
			{
				if (c is not ((>= '0' and <= '9') or (>= 'a' and <= 'f') or (>= 'A' and <= 'F'))) return "unidentified";
			}
			return projectId.Length <= 64 ? projectId : projectId.Substring(0, 64);
		}
	}
}
