<Project>
	<Import Project="TestProjects.props" />
	<PropertyGroup>
		<DefineConstants Condition=" '$(ContinuousIntegrationBuild)' == 'true' ">$(DefineConstants);SKIP_PLATFORM_TESTS</DefineConstants>
		<MSTestAnalysisMode>All</MSTestAnalysisMode>
		<RunSettingsFilePath>$(MSBuildProjectDirectory)/../MainSln.runsettings</RunSettingsFilePath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="$(ProjectDir)../../extern/tools/NLua/NLua.csproj" />
		<None Include="$(ProjectDir)../../build/dll/lua54.*" CopyToOutputDirectory="PreserveNewest" />
		<None Include="$(ProjectDir)../../build/dll/libbizhash.*" CopyToOutputDirectory="PreserveNewest" />
		<None Include="$(ProjectDir)../../build/dll/libzstd.*" CopyToOutputDirectory="PreserveNewest" />
		<Using Include="Chimera.Tests" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
	</ItemGroup>
	<PropertyGroup>
		<!-- Works around weird issue with IsExternalInit specifically, cause is likely related to https://github.com/Sergio0694/PolySharp/issues/48? -->
		<PolySharpExcludeTypeForwardedToDeclarations>true</PolySharpExcludeTypeForwardedToDeclarations>
	</PropertyGroup>
</Project>
