#!/usr/bin/env python3
"""Writes the crash module's table of GL entry-point names, numbered the way the
GPU bridge numbers them: miniBox's master list, first name opcode 100, blanks and
# comments ignored (the same reading as gen-gl-bridge.py's read_names).

usage: gen-gl-names.py <gl-entry-points.txt> <gl_names.h>
"""
import sys

if len(sys.argv) != 3:
    sys.exit(__doc__)
names = []
for line in open(sys.argv[1]):
    line = line.split("#", 1)[0].strip()
    if line:
        names.append(line)
with open(sys.argv[2], "w") as out:
    out.write("/* GENERATED by source/crash/gen-gl-names.py from miniBox's gl-entry-points.txt. */\n")
    out.write("#pragma once\n")
    out.write("#define GL_NAMES_FIRST_OPCODE 100u\n")
    out.write("#define GL_NAMES_COUNT %du\n" % len(names))
    out.write("static const char *const gl_names[%d] = {\n" % len(names))
    for name in names:
        out.write('\t"%s",\n' % name)
    out.write("};\n")
